[Style(name="backgroundSkin", type="Class", skinClass="true")]

[Style(name="backgroundSkin_backgroundAlpha", type="Number")]
[Style(name="backgroundSkin_backgroundColor", type="uint", format="Color")]
[Style(name="backgroundSkin_backgroundImage", type="Class")]
[Style(name="backgroundSkin_backgroundImageFillMode", type="String", enumeration="scale,clip,repeat")]
[Style(name="backgroundSkin_dropShadowVisible", type="Boolean")]
[Style(name="backgroundSkin_dropShadowAlpha", type="Number", format="Length")]
[Style(name="backgroundSkin_dropShadowAngle", type="Number", format="Length")]
[Style(name="backgroundSkin_dropShadowBlur", type="Number", format="Length")]
[Style(name="backgroundSkin_dropShadowColor", type="uint", format="Color")]
[Style(name="backgroundSkin_dropShadowDistance", type="Number", format="Length")]
[Style(name="backgroundSkin_dropShadowStrength", type="Number", format="Length")]
[Style(name="backgroundSkin_dropShadowInner", type="Boolean")]