[Style(name="borderSkin", type="Class", skinClass="true")]

[Style(name="borderSkin_borderStyle", type="String", enumeration="solid,none", invalidateSize="true", invalidateDisplayList="true")]
[Style(name="borderSkin_borderVisible", type="Boolean")]
[Style(name="borderSkin_borderColor", type="uint", format="Color")]
[Style(name="borderSkin_borderAlpha", type="Number")]
[Style(name="borderSkin_borderWeight", type="Number", format="Length", invalidateSize="true", invalidateDisplayList="true")]
[Style(name="borderSkin_cornerRadius", type="Number", format="Length")]

[Style(name="borderSkin_dropShadowVisible", type="Boolean")]
[Style(name="borderSkin_dropShadowAlpha", type="Number", format="Length")]
[Style(name="borderSkin_dropShadowAngle", type="Number", format="Length")]
[Style(name="borderSkin_dropShadowBlur", type="Number", format="Length")]
[Style(name="borderSkin_dropShadowColor", type="uint", format="Color")]
[Style(name="borderSkin_dropShadowDistance", type="Number", format="Length")]
[Style(name="borderSkin_dropShadowStrength", type="Number", format="Length")]
[Style(name="borderSkin_dropShadowInner", type="Boolean")]

[Style(name="borderSkin_backgroundColor", type="uint", format="Color")]
[Style(name="borderSkin_backgroundAlpha", type="Number")]
[Style(name="borderSkin_backgroundImage", type="Class")]
[Style(name="borderSkin_backgroundImageFillMode", type="String", enumeration="scale,clip,repeat")]