[Style(name="color", type="uint", format="Color", inherit="yes")]
//原disabledColor与Flex编译器冲突
[Style(name="disabledTextColor", type="uint", format="Color")]
[Style(name="textAlign", type="String", enumeration="left,center,right,justify", inherit="yes")]
[Style(name="fontWeight", type="String", enumeration="normal,bold", inherit="yes")]
[Style(name="fontStyle", type="String", enumeration="normal,italic", inherit="yes")]
[Style(name="textDecoration", type="String", enumeration="none,underline", inherit="yes")]
[Style(name="kerning", type="Boolean", inherit="yes")]
[Style(name="fontSize", type="Number", format="Length", inherit="yes")]
[Style(name="fontFamily", type="String", inherit="yes")]
[Style(name="textIndent", type="Number", format="Length", inherit="yes")]
[Style(name="letterSpacing", type="Number", inherit="yes")]
[Style(name="fontAntiAliasType", type="String", enumeration="normal,advanced", inherit="yes")]
[Style(name="fontThickness", type="Number", inherit="yes")]
[Style(name="fontGridFitType", type="String", enumeration="none,pixel,subpixel", inherit="yes")]
[Style(name="fontSharpness", type="Number", inherit="yes")]